services:

  mssql-blog:
    restart: always
    container_name: sql_server2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=werdwerd2012_
    volumes:
      - /home/sqlserver19-blog/data:/var/opt/mssql/data
      - /home/sqlserver19-blog/log:/var/opt/mssql/log
      - /home/sqlserver19-blog/secrets:/var/opt/mssql/secrets

  mssql-blog-dev:
    restart: always
    container_name: sql_server2019dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1434:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=werdwerd2012_
    volumes:
      - /home/sqlserver19-blog-dev/data:/var/opt/mssql/data
      - /home/sqlserver19-blog-dev/log:/var/opt/mssql/log
      - /home/sqlserver19-blog-dev/secrets:/var/opt/mssql/secrets

  blog:
    restart: always
    container_name: blog
    image: forevka/blog:latest
    user: root
    ports:
      - 1450:80
      - 1451:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - umb_media:/app/wwwroot/media
      - umb_logs:/app/umbraco/Logs

volumes:
  umb_media:
    driver: local
    driver_opts:
      type: none
      device: /home/docker/Blog/media
      o: bind
  umb_logs:
    driver: local
    driver_opts:
      type: none
      device: /home/docker/Blog/Logs
      o: bind