//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.2.0+41b7696
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>CodeBlockContentSettings</summary>
	[PublishedModel("codeBlockContentSettings")]
	public partial class CodeBlockContentSettings : PublishedElementModel, ITocEntry
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		public new const string ModelTypeAlias = "codeBlockContentSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<CodeBlockContentSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public CodeBlockContentSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// LanguageName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("languageName")]
		public virtual string LanguageName => this.Value<string>(_publishedValueFallback, "languageName");

		///<summary>
		/// LanguageTheme
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("languageTheme")]
		public virtual string LanguageTheme => this.Value<string>(_publishedValueFallback, "languageTheme");

		///<summary>
		/// IsEnabled
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[ImplementPropertyType("isEnabled")]
		public virtual bool IsEnabled => global::Umbraco.Cms.Web.Common.PublishedModels.TocEntry.GetIsEnabled(this, _publishedValueFallback);

		///<summary>
		/// TocAnchor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tocAnchor")]
		public virtual string TocAnchor => global::Umbraco.Cms.Web.Common.PublishedModels.TocEntry.GetTocAnchor(this, _publishedValueFallback);

		///<summary>
		/// TocLevel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[ImplementPropertyType("tocLevel")]
		public virtual int TocLevel => global::Umbraco.Cms.Web.Common.PublishedModels.TocEntry.GetTocLevel(this, _publishedValueFallback);

		///<summary>
		/// TocText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.2.0+41b7696")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tocText")]
		public virtual string TocText => global::Umbraco.Cms.Web.Common.PublishedModels.TocEntry.GetTocText(this, _publishedValueFallback);
	}
}
